# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
# Input:
# k = "aa"
# j = "a"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.
from collections import Counter

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        cCounter = Counter(s + t)
        for i in cCounter:
            if cCounter[i] %2 != 0:
                return i



